export default [
  {
    id: 1,
    city: 'Singapore',
    color: 'red',
    coordinates: [1.3521, 103.8198],
    value: 50,
  },
  {
    id: 2,
    city: 'New York',
    color: 'blue',
    coordinates: [40.73061, -73.935242],
    value: 25,
  },
  {
    id: 3,
    city: 'San Francisco',
    color: 'orange',
    coordinates: [37.773972, -122.431297],
    value: 35,
  },
  {
    id: 4,
    city: 'Beijing',
    color: 'gold',
    coordinates: [39.9042, 116.4074],
    value: 0,
  },
  {
    id: 5,
    city: 'London',
    color: 'green',
    coordinates: [51.5074, 0.1278],
    value: 2,
  },
  {
    id: 6,
    city: 'Paris',
    color: 'blue',
    coordinates: [48.8566, 2.3522],
    value: 2,
  },
  {
    id: 7,
    city: 'London',
    color: 'green',
    coordinates: [0.1, 0.2],
    value: 2,
  },
  {
    id: 8,
    city: 'London',
    color: 'green',
    coordinates: [0.1, 0.2],
    value: 2,
  },
  {
    id: 9,
    city: 'London',
    color: 'green',
    coordinates: [0.1, 0.2],
    value: 2,
  },
  {
    id: 10,
    city: 'London',
    color: 'green',
    coordinates: [0.1, 0.2],
    value: 2,
  },
  {
    id: 11,
    city: 'London',
    color: 'green',
    coordinates: [0.1, 0.2],
    value: 2,
  },
  {
    id: 12,
    city: 'London',
    color: 'green',
    coordinates: [0.1, 0.2],
    value: 2,
  },
  {
    id: 13,
    city: 'London',
    color: 'green',
    coordinates: [0.1, 0.2],
    value: 2,
  },
  {
    id: 14,
    city: 'London',
    color: 'green',
    coordinates: [0.1, 0.2],
    value: 2,
  },
  {
    id: 15,
    city: 'London',
    color: 'green',
    coordinates: [0.1, 0.2],
    value: 2,
  },
  {
    id: 16,
    city: 'London',
    color: 'green',
    coordinates: [0.1, 0.2],
    value: 2,
  },
  {
    id: 17,
    city: 'London',
    color: 'green',
    coordinates: [0.1, 0.2],
    value: 2,
  },
  {
    id: 18,
    city: 'London',
    color: 'green',
    coordinates: [0.1, 0.2],
    value: 2,
  },
  {
    id: 19,
    city: 'London',
    color: 'green',
    coordinates: [0.1, 0.2],
    value: 2,
  },
  {
    id: 20,
    city: 'London',
    color: 'green',
    coordinates: [0.1, 0.2],
    value: 2,
  }
];
